# Hardcoded mobile accessory data
from typing import List
from models import MobileAccessory


mobile_accessories: List[MobileAccessory] = [
    MobileAccessory(
        id=1,
        phone_model="iPhone 13 Pro",
        name="Transparent",
        price=499,
        currency="LKR",
        on_sale=True,
        image_uri="/static/accessories-photos/id_1.png",
        description="Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    ),
    MobileAccessory(
        id=2,
        phone_model="Samsung S23+",
        name="Transparent",
        price=799,
        currency="LKR",
        on_sale=False,
        image_uri="/static/accessories-photos/id_2.png",
        description="Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
    ),
    MobileAccessory(
        id=3,
        phone_model="iPhone 14",
        name="Transparent with magsafe",
        price=799,
        currency="LKR",
        on_sale=True,
        image_uri="/static/accessories-photos/id_3.png",
        description="Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris.",
    ),
    MobileAccessory(
        id=4,
        phone_model="Pixel 7 Pro",
        name="Transparent Wireless",
        price=599,
        currency="LKR",
        on_sale=True,
        image_uri="/static/accessories-photos/id_4.png",
        description="Nisi ut aliquip ex ea commodo consequat.",
    ),
    MobileAccessory(
        id=5,
        phone_model="Pixel 6a",
        name="Matte Black",
        price=499,
        currency="LKR",
        on_sale=False,
        image_uri="/static/accessories-photos/id_5.png",
        description="Duis aute irure dolor in reprehenderit in voluptate velit esse.",
    ),
    MobileAccessory(
        id=6,
        phone_model="Pixel 6a",
        name="Standard",
        price=399,
        currency="LKR",
        on_sale=True,
        image_uri="/static/accessories-photos/id_6.png",
        description="Cillum dolore eu fugiat nulla pariatur.",
    ),
    MobileAccessory(
        id=7,
        phone_model="iPhone 14",
        name="Transparent with magsafe",
        price=799,
        currency="LKR",
        on_sale=True,
        image_uri="/static/accessories-photos/id_7.png",
        description="Excepteur sint occaecat cupidatat non proident.",
    ),
    MobileAccessory(
        id=8,
        phone_model="Pixel 7 Pro",
        name="Transparent Wireless",
        price=599,
        currency="LKR",
        on_sale=False,
        image_uri="/static/accessories-photos/id_8.png",
        description="Sunt in culpa qui officia deserunt mollit anim id est laborum.",
    ),
    MobileAccessory(
        id=9,
        phone_model="iPhone 13 Pro",
        name="Transparent",
        price=499,
        currency="LKR",
        on_sale=False,
        image_uri="/static/accessories-photos/id_9.png",
        description="Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    ),
    MobileAccessory(
        id=10,
        phone_model="Samsung S23+",
        name="Transparent",
        price=799,
        currency="LKR",
        on_sale=True,
        image_uri="/static/accessories-photos/id_10.png",
        description="Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
    ),
    MobileAccessory(
        id=11,
        phone_model="Pixel 6a",
        name="Transparent",
        price=599,
        currency="LKR",
        on_sale=False,
        image_uri="/static/accessories-photos/id_11.png",
        description="Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris.",
    ),
    MobileAccessory(
        id=12,
        phone_model="Pixel 7 Pro",
        name="Transparent Wireless",
        price=599,
        currency="LKR",
        on_sale=False,
        image_uri="/static/accessories-photos/id_12.png",
        description="Nisi ut aliquip ex ea commodo consequat.",
    ),
    MobileAccessory(
        id=13,
        phone_model="iPhone 13 Pro",
        name="Transparent",
        price=499,
        currency="LKR",
        on_sale=True,
        image_uri="/static/accessories-photos/id_13.png",
        description="Duis aute irure dolor in reprehenderit in voluptate velit esse.",
    ),
    MobileAccessory(
        id=14,
        phone_model="Samsung S23+",
        name="Transparent",
        price=799,
        currency="LKR",
        on_sale=False,
        image_uri="/static/accessories-photos/id_14.png",
        description="Cillum dolore eu fugiat nulla pariatur.",
    ),
    MobileAccessory(
        id=15,
        phone_model="iPhone 14",
        name="Transparent with magsafe",
        price=799,
        currency="LKR",
        on_sale=False,
        image_uri="/static/accessories-photos/id_15.png",
        description="Excepteur sint occaecat cupidatat non proident.",
    ),
    MobileAccessory(
        id=16,
        phone_model="Pixel 7 Pro",
        name="Transparent Wireless",
        price=599,
        currency="LKR",
        on_sale=False,
        image_uri="/static/accessories-photos/id_16.png",
        description="Sunt in culpa qui officia deserunt mollit anim id est laborum.",
    ),
    MobileAccessory(
        id=17,
        phone_model="iPhone 13 Pro",
        name="Transparent",
        price=499,
        currency="LKR",
        on_sale=True,
        image_uri="/static/accessories-photos/id_1.png",
        description="Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    ),
    MobileAccessory(
        id=18,
        phone_model="Samsung S23+",
        name="Transparent",
        price=799,
        currency="LKR",
        on_sale=False,
        image_uri="/static/accessories-photos/id_2.png",
        description="Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
    ),
    MobileAccessory(
        id=19,
        phone_model="iPhone 14",
        name="Transparent with magsafe",
        price=799,
        currency="LKR",
        on_sale=True,
        image_uri="/static/accessories-photos/id_3.png",
        description="Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris.",
    ),
    MobileAccessory(
        id=20,
        phone_model="Pixel 7 Pro",
        name="Transparent Wireless",
        price=599,
        currency="LKR",
        on_sale=True,
        image_uri="/static/accessories-photos/id_4.png",
        description="Nisi ut aliquip ex ea commodo consequat.",
    ),
    MobileAccessory(
        id=21,
        phone_model="Pixel 6a",
        name="Matte Black",
        price=499,
        currency="LKR",
        on_sale=False,
        image_uri="/static/accessories-photos/id_5.png",
        description="Duis aute irure dolor in reprehenderit in voluptate velit esse.",
    ),
    MobileAccessory(
        id=22,
        phone_model="Pixel 6a",
        name="Standard",
        price=399,
        currency="LKR",
        on_sale=True,
        image_uri="/static/accessories-photos/id_6.png",
        description="Cillum dolore eu fugiat nulla pariatur.",
    ),
    MobileAccessory(
        id=23,
        phone_model="iPhone 14",
        name="Transparent with magsafe",
        price=799,
        currency="LKR",
        on_sale=True,
        image_uri="/static/accessories-photos/id_7.png",
        description="Excepteur sint occaecat cupidatat non proident.",
    ),
    MobileAccessory(
        id=24,
        phone_model="Pixel 7 Pro",
        name="Transparent Wireless",
        price=599,
        currency="LKR",
        on_sale=False,
        image_uri="/static/accessories-photos/id_8.png",
        description="Sunt in culpa qui officia deserunt mollit anim id est laborum.",
    ),
    MobileAccessory(
        id=25,
        phone_model="iPhone 13 Pro",
        name="Transparent",
        price=499,
        currency="LKR",
        on_sale=False,
        image_uri="/static/accessories-photos/id_9.png",
        description="Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    ),
    MobileAccessory(
        id=26,
        phone_model="Samsung S23+",
        name="Transparent",
        price=799,
        currency="LKR",
        on_sale=True,
        image_uri="/static/accessories-photos/id_10.png",
        description="Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
    ),
    MobileAccessory(
        id=27,
        phone_model="Pixel 6a",
        name="Transparent",
        price=599,
        currency="LKR",
        on_sale=False,
        image_uri="/static/accessories-photos/id_11.png",
        description="Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris.",
    ),
    MobileAccessory(
        id=28,
        phone_model="Pixel 7 Pro",
        name="Transparent Wireless",
        price=599,
        currency="LKR",
        on_sale=False,
        image_uri="/static/accessories-photos/id_12.png",
        description="Nisi ut aliquip ex ea commodo consequat.",
    ),
    MobileAccessory(
        id=29,
        phone_model="iPhone 13 Pro",
        name="Transparent",
        price=499,
        currency="LKR",
        on_sale=True,
        image_uri="/static/accessories-photos/id_13.png",
        description="Duis aute irure dolor in reprehenderit in voluptate velit esse.",
    ),
    MobileAccessory(
        id=30,
        phone_model="Samsung S23+",
        name="Transparent",
        price=799,
        currency="LKR",
        on_sale=False,
        image_uri="/static/accessories-photos/id_14.png",
        description="Cillum dolore eu fugiat nulla pariatur.",
    ),
    MobileAccessory(
        id=31,
        phone_model="iPhone 14",
        name="Transparent with magsafe",
        price=799,
        currency="LKR",
        on_sale=False,
        image_uri="/static/accessories-photos/id_15.png",
        description="Excepteur sint occaecat cupidatat non proident.",
    ),
    MobileAccessory(
        id=32,
        phone_model="Pixel 7 Pro",
        name="Transparent Wireless",
        price=599,
        currency="LKR",
        on_sale=False,
        image_uri="/static/accessories-photos/id_16.png",
        description="Sunt in culpa qui officia deserunt mollit anim id est laborum.",
    ),
]
